services:
  sip-signaling:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-sip-signaling-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_sip_signaling
    environment:
      # Rust kodumuz bu değişkenleri bekliyor, .env'den direkt alıyoruz.
      - SIP_HOST=0.0.0.0
      - SIP_PORT=${SIP_PORT}
      - PUBLIC_IP=${PUBLIC_IP}
      - USER_SERVICE_GRPC_URL=${USER_SERVICE_GRPC_URL}
      - DIALPLAN_SERVICE_GRPC_URL=${DIALPLAN_SERVICE_GRPC_URL}
      - MEDIA_SERVICE_GRPC_URL=${MEDIA_SERVICE_GRPC_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}    
    env_file:
      - ./.env
    ports:
      - "${SIP_PORT:-5060}:${SIP_PORT:-5060}/udp"
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge