# docker-compose.dev.yml
# Service Geliştirme ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

volumes:
  # [infra]: Temel Altyapı (Infrastructure Layer)
  # --------------------------------------------------
  rabbitmq_data:
  redis_data:

services:
  # [capability-telephony]: Yetenek Servisleri (Capability Layer)
  # --------------------------------------------------
  sip-signaling:
    build: { context: ../sentiric-sip-signaling-service }
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"
      - "${CERTIFICATES_REPO_PATH}:/sentiric-certificates:ro"
      - "${ASSETS_REPO_PATH}:/sentiric-assets:ro"    
    ports: 
      - "${SIP_SIGNALING_UDP_PORT:-13024}:${SIP_SIGNALING_UDP_PORT:-13024}/udp"
    networks:
      sentiric-net:
        ipv4_address: ${SIP_SIGNALING_IPV4_ADDRESS}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sentiric-sip-signaling-service || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s    
    # depends_on: 
    #   rabbitmq: { condition: service_healthy }
    #   media-service: { condition: service_healthy }
    #   redis: { condition: service_healthy }