services:
  sip-signaling:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-sip-signaling-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_sip_signaling
    # Bu satır, bu klasördeki .env dosyasını okuyarak
    # tüm ortam değişkenlerini otomatik olarak yükler.
    env_file:
      - ./.env
    # environment bloğunu kaldırıyoruz, çünkü env_file zaten bu işi yapıyor.
    # Bu, "değişkenler neden iki yerde tanımlı?" karışıklığını giderir.
    
    # ports ve networks tanımları ana 'infrastructure' compose dosyasından gelmeli.
    # Bu dosya sadece servisin nasıl 'build' edileceğini tanımlamalıdır.
    # Ancak test için burada bırakabiliriz.
    networks:
      - sentiric-net

networks:
  sentiric-net:
    # Bu ağın zaten 'infrastructure' tarafından oluşturulduğunu varsayıyoruz.
    external: true